package main

import (
	"github.com/gin-gonic/gin"
	cards "github.com/spenmo-jamboree/walletManagement/cards"
	"github.com/spenmo-jamboree/walletManagement/middlewares"

	_ "github.com/spenmo-jamboree/walletManagement/docs" // docs is generated by Swag CLI, you have to import it.
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

const (
	SWAGGER_URI      string = "http://localhost:8080/swagger/doc.json"
	SERVER_HOST_PORT string = "localhost:8080"
)

func RouterInit() {
	// Init router and middleware plugins
	router := gin.Default()
	router.Use(gin.Recovery())
	router.Use(middlewares.RateLimiter())

	// Init routes
	router.GET(cards.BaseRoute, cards.HandleGetCards)
	router.POST(cards.BaseRoute, cards.HandleCreateCards)

	// Init swagger serve TODO: disable in prod env
	url := ginSwagger.URL(SWAGGER_URI) // The url pointing to API definition
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	router.Run(SERVER_HOST_PORT)
}

func main() {
	RouterInit()
}
