package main

import (
	"github.com/gin-gonic/gin"

	cards "github.com/spenmo-jamboree/walletManagement/cards"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/spenmo-jamboree/docs" // docs is generated by Swag CLI, you have to import it.
)

func RouterInit() {
	router := gin.Default()
	// router.Use(DummyMiddleware())
	router.GET("/cards", cards.HandleGetCards)
	router.POST("/cards", cards.HandleCreateCards)
	// router.GET("/albums/:id", getAlbumByID)

	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	router.Run("localhost:8080")
}

func main() {
	RouterInit()
}
